/*************************************************
 * Stars and Stripes Forever Theme
 * by John Philip Sousa
 * 
 * Number of Notes: 82
 * Expected Duration: ~ 43 seconds
 *************************************************/

#include <avr/pgmspace.h>
#include "NoteLengths.h"

#define STARS_NUM_NOTES 82

const PROGMEM uint16_t StarsAndStripesMelody[] = {
  // 1
  NOTE_G5,
  NOTE_G5, NOTE_F5, NOTE_E5,
  NOTE_E5, NOTE_DS5, NOTE_E5,
  NOTE_E5,

  // 2
  NOTE_E5, NOTE_DS5, NOTE_E5,
  NOTE_E5, NOTE_DS5, NOTE_E5,
  NOTE_G5, NOTE_E5, NOTE_G5,
  NOTE_F5,

  // 3
  NOTE_D5, NOTE_D5,
  NOTE_D5, NOTE_CS5, NOTE_D5,
  NOTE_D5, NOTE_CS5, NOTE_D5,
  NOTE_F5, 

  // 4
  NOTE_F5, NOTE_E5, NOTE_D5,
  NOTE_E5, NOTE_G5,
  NOTE_A5, NOTE_A5,
  NOTE_D5,

  // 5
  NOTE_D5, REST, NOTE_G5,
  NOTE_G5, NOTE_F5, NOTE_E5,
  NOTE_E5, NOTE_DS5, NOTE_E5,
  NOTE_E5,

  // 6
  NOTE_E5, NOTE_DS5, NOTE_E5,
  NOTE_E5, NOTE_DS5, NOTE_E5,
  NOTE_F5, NOTE_E5, NOTE_D5, NOTE_B4,
  NOTE_D5,

  // 7
  NOTE_C5, NOTE_C5,
  NOTE_C5, NOTE_B4, NOTE_C5,
  NOTE_DS5, NOTE_D5, NOTE_C5,
  NOTE_C5,

  // 8
  NOTE_C5, NOTE_C5, NOTE_D5, NOTE_E5,
  NOTE_G5, NOTE_C5, NOTE_D5, NOTE_E5,
  NOTE_G5, NOTE_G4, NOTE_A5, NOTE_E5,
  NOTE_D5,

  // 9
  NOTE_C5, REST, NOTE_C6, REST,
};

const PROGMEM uint8_t StarsAndStripesDurations[] = {
 // 1
 HALF_NOTE,
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 WHOLE_NOTE,

 // 2
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 HALF_NOTE, THREE_EIGHTHS_NOTE, EIGHTH_NOTE,
 WHOLE_NOTE,

 // 3
 HALF_NOTE, HALF_NOTE,
 QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 WHOLE_NOTE,

 // 4
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 QUARTER_NOTE, THREE_QUARTERS_NOTE,
 THREE_QUARTERS_NOTE, QUARTER_NOTE,
 WHOLE_NOTE,

 // 5
 QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE,
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 WHOLE_NOTE,

 // 6
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, 
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 QUARTER_NOTE, QUARTER_NOTE, THREE_EIGHTHS_NOTE, EIGHTH_NOTE,
 WHOLE_NOTE,

 // 7
 HALF_NOTE, HALF_NOTE,
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 WHOLE_NOTE,

 // 8
 QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE,
 WHOLE_NOTE,

  // 9
 QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE, QUARTER_NOTE,
};
